name: Inline Python Hello World

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs: 
  run-inline:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Inline Python
        run: python -c "print('Hello World!')"
